### DISCUSSION TITLE
[Feature] Auth Webhook

### DISCUSSION THREAD

**Discussion by FreeWind6** [damongolding/immich-kiosk#213] [Feature request]
### I have searched the existing feature requests to make sure this is not a duplicate request.

- [X] Yes

### The feature

When sending a Webhook, it would be cool to send authorization data, for example, basic auth or api key

For example
```
webhooks:
  - url: "https://your-webhook-endpoint.com"
    event: asset.new
    login: login
    password: password
```
or
```
webhooks:
  - url: "https://your-webhook-endpoint.com"
    event: asset.new
    api-key: key
```
