### DISCUSSION TITLE
[Feature] Display custom data

### DISCUSSION THREAD

**Discussion by pe1uca** [damongolding/immich-kiosk#245] [Feature request]
### I have searched the existing feature requests to make sure this is not a duplicate request.

- [X] Yes

### The feature

I'd like a way to show custom data other than the available in the configuration.  

It'd be great to be able to add it in a similar way to the weather: a list of available options to show depending on a query parameter.  

Probably the simplest way would be to allow an HTTP request which should return an html to show in an iframe, or maybe a json with an array of strings force each one into a div?  
```yml
customServices:
  - name: bus
    url: https://custom.service.local/bus
    refreshTime: 60 # seconds to make another request for more data
```

Something really cool would be to have an option to show the data either in a corner, or as a banner in the top/bot middle of the screen, which could be configured to show the data scrolling (specially if the request should return an array of strings)
