### DISCUSSION TITLE
Predefined urls as  filter on frontend

### DISCUSSION THREAD

**Discussion by xydac** [damongolding/immich-kiosk#248] [Ideas]
This is just an idea -

1. Allowing configs to store key value mapping for id -> query params

2. Frontend to show list of those ids that can then be selected for given kiosk

This could allow for 

a) simplified way to switching between different views for non web devices where you don't want to type lengthy urls

b) switching context on kiosk - say you want to turn on todays picture or memories of this date over the year

**Comment by damongolding** [comment]
This is how the redirects work, unless I am misunderstanding. Well, apart from having the option to select from a list on the front end.

**Comment by xydac** [comment]
I was more focused on list in frontend, while i get that these redirects could be managed externally, you wouldn’t want to keep changing url every time you want to see a different view, Having a selectable list in frontend would be a good idea.

**Comment by johndoe0815** [comment]
With the great new date range filter option, I just had a similar idea. 
Would be really great if one could have a start page with the different parameters with default/env values that can be changed and are then added as URL parameters to a slideshow.
I am using immich kiosk on a tablet in the kitchen, and especially for the dates I'd like to change on demand to e.g. today let it show only pictures from 2023. Manually editing the URL on a tablet is quite cumbersome, so having a date picker and a button "start slideshow" would be really great for that.

**Comment by damongolding** [comment]
Something like this? 

![localhost_3000_ (1)](https://github.com/user-attachments/assets/7937f28b-e02a-47fa-8862-44fbcfef845f)

```yaml

kiosk:
  links:
    - name: christmas 2023
      url: /?date=2023-12-24_to_2023-12-25

    - name: christmas 2022
      url: /?date=2023-12-24_to_2023-12-25

    - name: christmas 2021
      url: /?date=2023-12-24_to_2023-12-25

    - name: album A
      url: /?date=2023-12-24_to_2023-12-25

    # ... etc... #

```

**Comment by RobWW** [comment]
This looks like a great feature!

One detail that would be very useful for me, if you have not considered it already:  I would like to be able to select from this list with the keyboard (such as using the cursor up, down, and enter key).

My use case is I control my picture frame with an IR Remote, using an Flirc USB dongle.  This device works by simply translating IR signals to keyboard presses, which it sends to the active window.

Some background:  currently I have the browser set up with multiple tabs for different parameters, and switch between the tabs with using the  Ctrl + Tab keyboard shortcut.  This works, but is somewhat of a guessing game, as in fullscreen mode there is no user interface on the browser showing what tab (and therefore parameters) is selected.

**Reply by damongolding** [reply]
I'll have a think about it. It's not straight forward as the up/down arrows are not standard keyboard navigation in browsers. It's possible of course but will need a bit more work.

**Comment by damongolding** [comment]
You can test out the new redirect GUI using this image `damongolding/immich-kiosk-development:0.15.1-beta.2`.

You can open the overlay via the menu or by hitting "r" on your keyboard.

It pulls in any redirects you have and displays them.

```yaml
kiosk:
  redirects:
    - name: christmas 2023
      url: /?date=2023-12-24_to_2023-12-25

    - name: christmas 2022
      url: /?date=2023-12-24_to_2023-12-25

    - name: christmas 2021
      url: /?date=2023-12-24_to_2023-12-25

    # ... etc ... #
```
