### DISCUSSION TITLE
Weather is displayed in an odd location, how do I fix it?

### DISCUSSION THREAD

**Discussion by tehniemer** [damongolding/immich-kiosk#255] [Q&A] [answered]
I have photo date and location info showing on the other side in what I would consider the correct location, but the weather info is biased upwards, how do I fix this?

![image](https://github.com/user-attachments/assets/641dbcd1-fa5d-4625-bcd9-37fcdebbd4b5)

**Comment by damongolding** [comment]
Mind posting your config files?

Are you using any custom css?

Also, what is Kiosk being displayed on?

**Comment by tehniemer** [comment]
No custom css.
It's just a chrome browser app on an android digital photo frame. I did attempt to make chrome immersive by running `adb shell settings put global policy_control immersive.full=com.android.chrome`

Here's the sanitized config.
```
# Required settings
immich_api_key: "xxxx"
immich_url: "xxxx"

# Clock
show_time: true # true or false
time_format: 12 # 12 or 24
show_date: true # true or false
date_format: MM/DD/YYYY

# Kiosk behaviour
refresh: 60 # in seconds
disable_screensaver: false # Ask browser to request a lock that prevents device screens from dimming or locking.

# Asset sources
show_archived: false # Allow assets marked as archived to be displayed.
person: # ID(s) of person or people to display
  - "xxxx" 
  - "xxxx"
album: # ID(s) of album or albums to display
  - ""
# UI
disable_ui: false # this is just a shortcut for all ui elements (show_time, show_date, show_image_time, show_image_date)
hide_cursor: false # Hide cursor/mouse via CSS.
font_size: 100 # the base font size as a percentage. OMIT the % character
background_blur: true # display a blurred version of image as background
theme: fade # which theme to use. fade or solid
layout: single # which layout to use. single or splitview

# Sleep mode
# sleep_start: 22 # sleep mode start time
# sleep_end: 7 # sleep mode end time

# Transition options
transition: fade # cross-fade, fade or none
fade_transition_duration: 1 # in seconds
cross_fade_transition_duration: 1 # in seconds

# Image display settings
show_progress: false # display a progress bar
image_fit: contain # how the image fits the screen. Options are none, contain and cover
image_zoom: false # add a zoom effect to images
image_zoom_amount: 120 # The amount zoomed as a percentage

# Image METADATA
show_image_time: false # true or false
image_time_format: 12 # 12 or 24
show_image_date: true # true or false
image_date_format: MM/DD/YYYY
show_image_exif: false
show_image_location: true

# Weather settings
weather:
 - name: Stillwater
   lat: xxxx
   lon: xxxx
   api: xxxx
   unit: imperial
   lang: en
   default: true

# options that can NOT be changed via url params
kiosk:
  password: ""
  cache: true # cache select api calls
  pre_fetch: true # fetch assets in the background
  asset_weighting: true # use weighting when picking assets
```
