### DISCUSSION TITLE
Multiple user with portainer

### DISCUSSION THREAD

**Discussion by Claudinetto2** [damongolding/immich-kiosk#313] [General]
Hi,
i have two users in immich with two different api keys and i want to show in kios 2 different people, one in user1 and the other in user2. Is it possibile? I use portainer to deploy the container and i have tried to do this

```yaml
services:
  immich-kiosk:
    image: damongolding/immich-kiosk:latest
    container_name: immich-kiosk
    environment:
      LANG: "it_IT"
      TZ: "Europe/Rome"
      KIOSK_IMMICH_API_KEY: "api_user_1"
      KIOSK_IMMICH_USERS_API_KEYS: 'user2: "api_user_2"'
      KIOSK_IMMICH_URL: "http://192.168.0.42:8212"
      KIOSK_SHOW_TIME: false
      KIOSK_TIME_FORMAT: 24
      KIOSK_SHOW_DATE: false
      KIOSK_DATE_FORMAT: DD/MM/YYYY
```

but it doesn't work, if i go to http://192.168.0.1:3000/?user=user2 i have "no api key found for user2

**Comment by damongolding** [comment]
You can only set multiple users in a `config.yaml` file, not from environment variables.

**Reply by Claudinetto2** [reply]
Ok i have do it and set 2 different users. It work only with all Photos. If i set 2 persons (1 per user) it doesn’t work, neither with url query

**Reply by damongolding** [reply]
Please share your `config.yaml` file and the url(s) you are trying to use

**Comment by Claudinetto2** [comment]
config.yaml is:

```
## Required settings - move these to ENV if you want to check in this file
immich_api_key: "kwVmdfsge34tgISkNcHEyuez8CKmMMbWCteDqwadwT"
immich_url: "http://192.168.0.1:8212"

## Clock
show_time: false
time_format: 24 # 12 or 24
show_date: false
date_format: YYYY/MM/DD

## Kiosk behaviour
refresh: 60 # in seconds
disable_screensaver: false # Ask browser to request a lock that prevents device screens from dimming or locking.
optimize_images: false # Whether Kiosk should resize images to match your browser screen dimensions for better performance.
use_gpu: true # Enable GPU acceleration for improved performance.

## Asset sources
show_archived: false # Allow assets marked as archived to be displayed.

## ID(s) of person or people to display
person:
  - "1dd32rv3d-a508-44ee-add8-7cefre51b509a9"
  - "q3wfeveb21-9e04-454e-a30c-f33e081796e4"
  
## ID(s) of album or albums to display
album:
  - "ALBUM_ID"
## Album IDs to exclude from being shown. Albums in this list will be filtered from
## appearing in the frame even if they are included in the 'album' list.
album_order: random # random | newest | oldest
excluded_albums:
  - "ALBUM_ID"

## Date range or ranges to display
date:
  - "YYYY-MM-DD_to_YYYY-MM-DD"

## Value(s) of tag(s) to display
tag:
  - "TAG_VALUE"

memories: false # show memories

## Filters
# date_filter: last-30-days # only applies to people and random assets

## Experimental
experimental_album_video: false

## UI
disable_ui: false # this is just a shortcut for all ui elements (show_time, show_date, show_image_time, show_image_date)
frameless: false # remove border around image and rounded corners.
hide_cursor: false # Hide cursor/mouse via CSS.
font_size: 100 # the base font size as a percentage. OMIT the % character
background_blur: true # display a blurred version of image as background
theme: fade # which theme to use. fade or solid
layout: single # which layout to use. single | splitview | splitview-landscape | portrait | landscape

## Sleep mode
# sleep_start: 22 # sleep mode start time
# sleep_end: 7 # sleep mode end time
sleep_icon: true

## Transition options
transition: none # cross-fade, fade or none
fade_transition_duration: 1 # in seconds
cross_fade_transition_duration: 1 # in seconds

## Image display settings
show_progress: false # display a progress bar
image_fit: contain # none | contain | cover
image_effect: none # none | zoom | smart-zoom
image_effect_amount: 120
use_original_image: false # use the original file.

## Image METADATA
show_album_name: false
show_person_name: false
show_image_time: false
image_time_format: 24 # 12 or 24
show_image_date: false
image_date_format: YYYY-MM-DD
show_image_description: false
show_image_exif: false
show_image_location: false
hide_countries:
  - "country to hide"
show_image_id: false
show_more_info: true
show_more_info_image_link: true
show_more_info_qr_code: true

## Weather feature - you’ll need an API key from OpenWeatherMap
# weather:
#   - name: london
#     lat: 51.5285262
#     lon: -0.2663999
#     api: ""
#     unit: metric
#     lang: en

## Immich API keys for specific users
immich_users_api_keys:
  user1: "kwVmdfsge34tgISkNcHEyuez8CKmMMbWCteDqwadwT"
  user2: "YGSqwkiUvVy5aV7GiYPqc8oaOE8efrvEmig4IYjmRpAaU"
show_user: true # show user name

## Options that can NOT be changed via url params
kiosk:
  port: 3000
  watch_config: false
  fetched_assets_size: 1000
  http_timeout: 20
  password: "0000"
  cache: true # cache select api calls
  pre_fetch: true # fetch assets in the background
  asset_weighting: true # use weighting when picking assets
```

with http://192.168.0.42:3000/?password=0000 
_selectin image: getting person image count: unexpected status code: 400_


at http://192.168.0.42:3000/?password=0000&user=user1
_user "user1" has no person  q3wfeveb21-9e04-454e-a30c-f33e081796e4_

at http://192.168.0.42:3000/?password=0000&user=user2
_user "user2" has no person  1dd32rv3d-a508-44ee-add8-7cefre51b509a9_

at http://192.168.0.42:3000/?password=0000&user=user1&person=1dd32rv3d-a508-44ee-add8-7cefre51b509a9 or http://192.168.0.42:3000/?password=0000&user=user2&person=q3wfeveb21-9e04-454e-a30c-f33e081796e4 work

at http://192.168.0.42:3000/?password=0000&user=user1&person=1dd32rv3d-a508-44ee-add8-7cefre51b509a9&&user=user2&person=q3wfeveb21-9e04-454e-a30c-f33e081796e4
_user "user1" has no person  q3wfeveb21-9e04-454e-a30c-f33e081796e4 or _user "user2" has no person  1dd32rv3d-a508-44ee-add8-7cefre51b509a9_
