### ISSUE TITLE
Can't connect to Immich Server on the same host

### ISSUE THREAD

**Issue by DrakeHamString** [damongolding/immich-kiosk#106]
**Describe the bug**
Getting a connection error despite Immich Kiosk and Immich Server being on the same host

**To Reproduce**
1. Install Immich Kiosk using the [Docker Compose template](https://github.com/damongolding/immich-kiosk?tab=readme-ov-file#docker-compose). Immich Kiosk and Immich Server are on the same host and share the same IP address.
2. Opening Immich Kiosk in the browser (or open an album provided in the URL querries)
3. Error "i/o timeout"

**Expected behavior**
Displaying contents of Immich (no error)

**Screenshots**
![image](https://github.com/user-attachments/assets/fa340d74-73a8-4094-a224-86e9e0ed7a4c)

**Your Kiosk version**
0.10.0

**Your Kiosk installation**
- Docker

**Your Kiosk ENV or config file**
```YAML
services:
  immich-kiosk:
    image: damongolding/immich-kiosk:latest
    container_name: immich-kiosk
    environment:
      TZ: "Europe/Berlin"
      KIOSK_IMMICH_API_KEY: "*****"
      KIOSK_IMMICH_URL: "http://*****:*****"
      # Clock
      KIOSK_SHOW_TIME: FALSE
      KIOSK_TIME_FORMAT: 24
      KIOSK_SHOW_DATE: FALSE
      KIOSK_DATE_FORMAT: "DD.MM.YYYY"
      # Kiosk behaviour
      KIOSK_REFRESH: 20
      KIOSK_DISABLE_SCREENSAVER: TRUE
      # Image metadata
      KIOSK_SHOW_IMAGE_TIME: FALSE
      KIOSK_IMAGE_TIME_FORMAT: 24
      KIOSK_SHOW_IMAGE_DATE: FALSE
      KIOSK_IMAGE_DATE_FORMAT: "DD.MM.YYYY"
      KIOSK_SHOW_IMAGE_EXIF: FALSE
      KIOSK_SHOW_IMAGE_LOCATION: FALSE
      # Kiosk settings
      KIOSK_CACHE: TRUE
      KIOSK_PREFETCH: TRUE
      KIOSK_ASSET_WEIGHTING: TRUE
    volumes:
      - /share/Container/Immich_Kiosk/config.yaml:/config.yaml
    restart: on-failure
    ports:
      - 3000:3000
```

**Any parms passed to the URL used to access Kiosk**
- http://****/?album=*****

**Additional context**
I noticed that when using the Docker Compose template's way to add a host mapped volume (but with a modified path) it creates an empty folder called "config.yaml" indead of an actual YAML file.

I also found no way to debug this because when trying to access the container's console (`/bin/bash`) via Portainer, it closes immediately again:
![304ae03c6601f9d01a3bc6654b0f988f](https://github.com/user-attachments/assets/ee126caa-e943-4415-808b-e3becc97e0b9)
