### ISSUE TITLE
The /refresh/check interface returns a 401 error when the password parameter is set, causing the nowifi icon to be displayed all the time.

### ISSUE THREAD

**Issue by zgr0629** [damongolding/immich-kiosk#148]
**Describe the bug**
The /refresh/check interface returns a 401 error when the password parameter is set, causing the nowifi icon to be displayed all the time.

**To Reproduce**
1. set password in config file
2. open kiosk web page with password parameter, like: http://yourkiosk.com?passowrd=yourpass
3. See no wifi icon all the time at the top of the page.

**Expected behavior**

**Screenshots**

<img width="852" alt="image" src="https://github.com/user-attachments/assets/65fd527e-542b-4c1c-a303-1582a7fd8f0d">

<img width="619" alt="image" src="https://github.com/user-attachments/assets/814a04ea-2bd6-4245-8b41-3f3804a47d72">

**Your Kiosk version**
0.11.3

**Your Kiosk installation**
Docker

**Your Kiosk ENV or config file**

```
# Required settings
immich_api_key: "xxxxxx"
immich_url: "immich-server:2283"

# Clock
show_time: false # true or false
time_format: 24 # 12 or 24
show_date: false # true or false
date_format: YYYY/MM/DD

# Kiosk behaviour
refresh: 7 # in seconds
disable_screensaver: true # Ask browser to request a lock that prevents device screens from dimming or locking.

# Asset sources
show_archived: false # Allow assets marked as archived to be displayed.
person: # ID(s) of person or people to display
  - ""
album: # ID(s) of album or albums to display
  - "all"
# UI
disable_ui: false # this is just a shortcut for all ui elements (show_time, show_date, show_image_time, show_image_date)
hide_cursor: false # Hide cursor/mouse via CSS.
font_size: 100 # the base font size as a percentage. OMIT the % character
background_blur: true # display a blurred version of image as background
theme: fade # which theme to use. fade or solid
layout: splitview # which layout to use. single or splitview

# Sleep mode
sleep_start: 22 # sleep mode start time
sleep_end: 7 # sleep mode end time

# Transition options
transition: none # cross-fade, fade or none
fade_transition_duration: 1 # in seconds
cross_fade_transition_duration: 1 # in seconds

# Image display settings
show_progress: true # display a progress bar
image_fit: contain # how the image fits the screen. Options are none, contain and cover
image_zoom: true # add a zoom effect to images
image_zoom_amount: 110 # The amount zoomed as a percentage

# Image METADATA
show_image_time: false # true or false
image_time_format: 24 # 12 or 24
show_image_date: true # true or false
image_date_format: YYYY-MM-DD
show_image_exif: true
show_image_location: true

# options that can NOT be changed via url params
kiosk:
  password: "yourpass"
  cache: true # cache select api calls
  pre_fetch: true # fetch assets in the background
  asset_weighting: true # use weighting when picking assets
```

**Any parms passed to the URL used to access Kiosk**
- http://****/??password=yourpass&album=xxxxxxx
- 

**Desktop:**
 - OS: macos
 - Browser chrome

**Additional context**
