### ISSUE TITLE
fillscreen has no effect?

### ISSUE THREAD

**Issue by zach-sb** [damongolding/immich-kiosk#20]
When trying to set `fill_screen=true` it has no obvious effect. However, if I edit the css for fillscreen from

```css
.frame--image-fillscreen {
    width: 100%;
    height: 100%;

    object-fit: contain;
}
```
![Screenshot 2024-07-27 085141](https://github.com/user-attachments/assets/139f2d49-494e-4a0e-9a10-0439d4477984)
to 
```css
.frame--image-fillscreen {
    width: 100%;
    height: 100%;

    object-fit: cover;
}
```

![Screenshot 2024-07-27 085121](https://github.com/user-attachments/assets/14ed9b05-ff96-437c-b5f1-f2162d8ddd79)

The image displays as I would expect from the name. I'm okay with it being centered like it does by default, I just didn't want any background at all.
