### ISSUE TITLE
clientName not found in request webhook

### ISSUE THREAD

**Issue by FreeWind6** [damongolding/immich-kiosk#217]
**Describe the bug**

**To Reproduce**
1. Open http://192.168.1.100:3000/?clientName=ipad
2. Send webhook
3. clientName not found in request

**Expected behavior**
clientName found in request

main.yml
```
services:
  immich-kiosk:
    container_name: immich-kiosk
    environment:
      TZ: Europe/Moscow
    image: damongolding/immich-kiosk:0.14.2
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - /mnt/MainPool/Media/immich-kiosk/config:/config
```

config.yml
```
# Required settings
immich_api_key: "*******"
immich_url: "***"

# Clock
show_time: true # true or false
show_date: true # true or false

refresh: 15

album:
  - "c6033ca7-caec-4bfe-8e22-5dc4e24e5bc2"

hide_cursor: true

sleep_start: 0
sleep_end: 8

transition: cross-fade

show_image_date: true
show_image_exif: true
show_image_location: true

kiosk:
  port: 3000
  redirects:
    - name: ipad
      url: /?clientName=ipad
    - name: mel
      url: /?clientName=mel

# Конфигурация доп инфо (кнопка i)
immich_external_url: "https://****.com"

webhooks:
  - url: "http://192.168.1.55:8080/home/api/immich-kiosk/webhook"
    event: user.webhook.trigger.info_overlay
    secret: "*****"
```
