### ISSUE TITLE
URL pointing directly to personID is sometimes showing assets from configured album

### ISSUE THREAD

**Issue by VenomousViper27** [damongolding/immich-kiosk#225]
I'm using URL redirect to show images for a particular person. When I go to that URL, every once in a while I will see images from my album configured in the config.yaml instead of just this personID. 

Just for clarification, I'm expecting this to show any images for this personID, not just images for this personID within the configured albumID. I noted that this behavior is reproducible if I go directly to the full person URL, so I don't believe the redirect logic is at fault.

**To Reproduce**
Load URL for person1, wait and see as it cycles through assets. It will display images at times that are in the defined album instead of this personID.

**Expected behavior**
I'm expecting the url /person1 to only show assets for that particular personID

**Your Kiosk version**
0.14.4

**Your Kiosk installation**
- Docker Compose

**Your Kiosk ENV or config file**
config.yaml

```
# Required settings
immich_api_key: "REMOVED"
immich_url: "REMOVED"
#immich_url: "REMOVED"

# Clock
show_time: true # true or false
time_format: 12 # 12 or 24
show_date: false # true or false
date_format: YYYY/MM/DD

# Kiosk behaviour
refresh: 240 # in seconds
disable_screensaver: false # Ask browser to request a lock that prevents device screens from dimming or locking.

# Asset sources
show_archived: false # Allow assets marked as archived to be displayed.

# ID(s) of person or people to display
person:
  - "PERSON_ID"

# ID(s) of album or albums to display
album:
  - a20f95a4-2877-497e-8b31-c00e13b18bca

# UI
disable_ui: false # this is just a shortcut for all ui elements (show_time, show_date, show_image_time, show_image_date)
hide_cursor: false # Hide cursor/mouse via CSS.
font_size: 100 # the base font size as a percentage. OMIT the % character
background_blur: false # display a blurred version of image as background
theme: fade # which theme to use. fade or solid
layout: single # which layout to use. single or splitview

# Sleep mode
#sleep_start: 22 # sleep mode start time
#sleep_end: 7 # sleep mode end time

# Transition options
transition: cross-fade # cross-fade, fade or none
fade_transition_duration: 1 # in seconds
cross_fade_transition_duration: 1 # in seconds

# Image display settings
show_progress: true # display a progress bar
image_fit: contain # how the image fits the screen. Options are none, contain and cover
image_zoom: false # add a zoom effect to images
image_zoom_amount: 120 # The amount zoomed as a percentage

# Image METADATA
show_image_time: false # true or false
image_time_format: 24 # 12 or 24
show_image_date: true # true or false
image_date_format: MMMM D, YYYY
show_image_exif: false
show_image_location: true
show_image_id: false
hide_countries: "United States of America"

# options that can NOT be changed via url params
kiosk:
  watch_config: true
  password: ""
  cache: true # cache select api calls
  pre_fetch: true # fetch assets in the background
  asset_weighting: true # use weighting when picking assets
  redirects:
    - name: person1
      url: /?person=6ac5257e-5f02-4a39-9f84-9bcfd64029cf&refresh=60&show_time=false
      type: internal

```
