### ISSUE TITLE
Only the latest album is shown

### ISSUE THREAD

**Issue by FreeWind6** [damongolding/immich-kiosk#235]
**Describe the bug**

**To Reproduce**
1. Go to https://***.***.com/?password=*******&album=2f0b8462-23f1-41d2-932f-3e934aacae9b&album=b40f41bb-7ceb-4e4d-943f-749ee36a0826
2. Only the latest album is shown (bug) - b40f41bb-7ceb-4e4d-943f-749ee36a0826
3. Go to https://***.***.com/?password=*******&album=b40f41bb-7ceb-4e4d-943f-749ee36a0826&album=2f0b8462-23f1-41d2-932f-3e934aacae9b
4. Only the latest album is shown (bug) - 2f0b8462-23f1-41d2-932f-3e934aacae9b

**Comment by FreeWind6** [comment]
Config

```
# Required settings
immich_api_key: ****
immich_url: *****

# Clock
show_time: true # true or false
show_date: true # true or false

refresh: 15

album:
  - "c6033ca7-caec-4bfe-8e22-5dc4e24e5bc2"

hide_cursor: true

sleep_start: 0
sleep_end: 8

transition: cross-fade

show_image_date: true
show_image_exif: true
show_image_location: true

weather:
  - name: moscow
    lat: 55.584200
    lon: 37.667350
    api: "abb6532ab50d07f26f4ae8130586ae17"
    unit: metric
    lang: ru
    default: true
  - name: stupino
    lat: 54.886280
    lon: 38.078237
    api: "abb6532ab50d07f26f4ae8130586ae17"
    unit: metric
    lang: ru

kiosk:
  port: 3000
  password: *****
  redirects:
    - name: ipad
      url: /?client=ipad
    - name: melnikov
      url: /?client=melnikov&weather=stupino&show_image_exif=false&album=b40f41bb-7ceb-4e4d-943f-749ee36a0826&album=c6033ca7-caec-4bfe-8e22-5dc4e24e5bc2

# Конфигурация доп инфо (кнопка i)
immich_external_url: "https://****.com"
```

**Comment by FreeWind6** [comment]
docker compose

```
services:
  immich-kiosk:
    container_name: immich-kiosk
    environment:
      TZ: Europe/Moscow
    image: damongolding/immich-kiosk:0.14.5
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - /mnt/MainPool/Media/immich-kiosk/config:/config
```
