### ISSUE TITLE
Invalid URL when clicking the `View image in Immich` button or scanning QR code if the internal container service name is used as `KIOSK_IMMICH_URL`

### ISSUE THREAD

**Issue by Trainax** [damongolding/immich-kiosk#246]
**Describe the bug**
Hello, I have set up Immich-Kiosk inside the same `docker-compose.yml` file as Immich, so I configured the `KIOSK_IMMICH_URL` variabile using the internal name instead of a URL. For this reason when I click on the `View image in Immich` button or I scan the QR code I get redirected to an invalid URL (`http://immich-server:2283/photos/ID`).

**To Reproduce**
1. Setup Immich-Kiosk like I've done
2. Start up Immich-Kiosk
3. When viewing an image click on the center of the screen, then on the `i` button
4. Click on the `View image in Immich` button or scan the QR code
5. Get redirected to an invalid URL (`http://immich-server:2283/photos/ID`)

**Expected behavior**: Get redirected to the correct Immich public URL.

**Your Kiosk version**: v0.14.7

**Your Kiosk installation**: Docker Compose

**Your Kiosk ENV or config file**: My `docker-compose.yml` file is as follows:

```YAML
name: immich
services:
  immich-server:
    ...
  immich-machine-learning:
    ...
  redis:
    ...
  database:
    ...
  immich-kiosk:
    image: damongolding/immich-kiosk:latest
    container_name: immich-kiosk
    environment:
      TZ: Europe/Rome
      KIOSK_IMMICH_API_KEY: (API key)
      KIOSK_IMMICH_URL: immich-server:2283
      KIOSK_DISABLE_UI: false
      KIOSK_SHOW_DATE: true
      KIOSK_DATE_FORMAT: DD/MM/YYYY
      KIOSK_SHOW_TIME: true
      KIOSK_TIME_FORMAT: 24
      KIOSK_REFRESH: 30
      KIOSK_ALBUM: (Kiosk album ID)
      #      KIOSK_PERSON: "PERSON_ID,PERSON_ID,PERSON_ID"
      KIOSK_IMAGE_FIT: CONTAIN
      KIOSK_BACKGROUND_BLUR: true
      KIOSK_TRANSITION: cross-fade
      KIOSK_SHOW_PROGRESS: true
      KIOSK_SHOW_IMAGE_TIME: true
      KIOSK_IMAGE_TIME_FORMAT: 24
      KIOSK_SHOW_IMAGE_DATE: true
      KIOSK_IMAGE_DATE_FORMAT: DD/MM/YYYY
    ports:
      - 3000:3000
    restart: unless-stopped
    
```

**Any parms passed to the URL used to access Kiosk**: None, the album ID is set as an environment variable inside the `docker-compose.yml` file.

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 133.0.3

**Additional context**
- Setting the "correct" Immich URL as the `KIOSK_IMMICH_URL` environment variabile is not the best option because maybe Immich is exposed to the Internet using a tunnel (like Cloudflare Tunnels) and that would mean going through the tunnel each time to fetch an Image which resides on the same machine Immich-Kiosk is running on.
- This could be solved by using a separate environment variabile (something like `KIOSK_IMMICH_PUBLIC_URL`) to generate links and QR codes.

Thank you so much for your work, it is much appreciated!
