### ISSUE TITLE
clearing cache

### ISSUE THREAD

**Issue by aviv926** [damongolding/immich-kiosk#247]
**Describe the bug**

I'm not sure, but is there a mechanism that clears the cache after X amount of time automatically? Changes I make to the album are only visible after a long time, is there a possibility to control this to determine how often the cache will be emptied?

**To Reproduce**
1. Set to pull photos from an album
2. Change the photos in the album
3. Wait a long time to see the changes

**Expected behavior**
Empty cache when updating album

**Screenshots**

**Your Kiosk version**
v0.14.7

**Your Kiosk installation**
- Docker

**Your Kiosk ENV or config file**

```
# Required settings
immich_api_key: "lVnOSh****AkbHAIiRjA"
immich_url: "192.168.1.153:2283"

# Clock
show_time: true
time_format: 24 # 12 or 24
show_date: true # true or false
date_format: DD/MM/YYYY

# Kiosk behaviour
refresh: 6 # in seconds
disable_screensaver: false # Ask browser to request a lock that prevents device screens from dimming or locking.

# Asset sources
show_archived: false # Allow assets marked as archived to be displayed.

# ID(s) of person or people to display
person:
  - "PERSON_ID"

# ID(s) of album or albums to display
album:
  - "1e712f1c-f57c-4608-89f0-2307b583d3b9"
# Album IDs to exclude from being shown. Albums in this list will be filtered from
# appearing in the frame even if they are included in the 'album' list.
excluded_albums:
  - "ALBUM_ID"

# UI
disable_ui: false # this is just a shortcut for all ui elements (show_time, show_date, show_image_time, show_image_date)
frameless: false # remove border around image and rounded corners.
hide_cursor: false # Hide cursor/mouse via CSS.
font_size: 150 # the base font size as a percentage. OMIT the % character
background_blur: true # display a blurred version of image as background
theme: fade # which theme to use. fade or solid
layout: splitview # which layout to use. single, splitview or splitview-landscape

# Sleep mode
# sleep_start: 22 # sleep mode start time
# sleep_end: 7 # sleep mode end time
sleep_icon: true

# Transition options
transition: fade # cross-fade, fade or none
fade_transition_duration: 1 # in seconds
cross_fade_transition_duration: 1 # in seconds

# Image display settings
show_progress: false # display a progress bar
image_fit: none # how the image fits the screen. Options are none, contain and cover
image_effect:
image_effect_amount: 260
use_original_image: false # use the original file.

# Image METADATA
show_image_time: false # true or false
image_time_format: 24 # 12 or 24
show_image_date: false # true or false
image_date_format: YYYY-MM-DD
show_image_description: false
show_image_exif: false
show_image_location: false
hide_countries:
  - "country to hide"
show_image_id: false
show_more_info: true
show_more_info_image_link: true
show_more_info_qr_code: true


# options that can NOT be changed via url params
kiosk:
  port: 3000
  watch_config: false
  fetched_assets_size: 1000
  http_timeout: 20
  password: ""
  cache: true # cache select api calls
  pre_fetch: true # fetch assets in the background
  asset_weighting: true # use weighting when picking assets

```

**Any parms passed to the URL used to access Kiosk**
- no

**Smartphone:**
Frame tablet with firefox  

**Additional context**
