### ISSUE TITLE
Won't use config.yaml file

### ISSUE THREAD

**Issue by jfreak53** [damongolding/immich-kiosk#249]
I can't get it to use config.yaml file to pull weather info. Everything else works fine. Here is my docker file:

`volumes:
      - ./config/config.yaml:/config.yaml`

And here is my config.yaml file:

```
weather:
  - name: myplace
    lat: XXX
    lon: XXX
    api: "XXX"
    unit: imperial
    lang: en
    default: true
```

But everytime I restart the service the logs tell me its not using them:

```
Version 0.14.7

10:02:50 INFO Not using config.yaml

Kiosk listening on port 3000

10:02:51 WARN weather data fetch attempt failed attempt=1 location=myplace
```
