### ISSUE TITLE
Custom CSS not applying?

### ISSUE THREAD

**Issue by FluffyClaws** [damongolding/immich-kiosk#250]
**Describe the bug**
Custom CSS not applying for some reason. Me being stupid is one of the possible ones...

The instructions in the docs - https://github.com/damongolding/immich-kiosk?tab=readme-ov-file#custom-css are also not very correct and\or clear, it says to map the file as a volume ./custom.css, but its not possible it returns an error when starting container:

`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/immich-kiosk/custom.css" to rootfs at "/custom.css": mount src=/immich-kiosk/custom.css, dst=/custom.css, dstFd=/proc/thread-self/fd/9, flags=0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

**To Reproduce**
1. Create a set of custom CSS at ./custom.css/custom.css
2. Map ./custom.css/custom.css in the docker-compose.
4. Start the container
6. See if it has been applied

**Screenshots**
![immich-kiosk-custom-css](https://github.com/user-attachments/assets/6c9b6c80-e95c-4c2b-b4c0-0c2d2707982d)
On the right in terminal it`s seen that volume is correctly mapped in container with its contents.

**Kiosk version**
0.14.7

**Your Kiosk installation**
Docker 27.4.1

**Kiosk ENV**
```
services:
  immich-kiosk:
    image: damongolding/immich-kiosk:latest
    container_name: immich-kiosk
    tty: true
    environment:
      TZ: "TZ=Europe/Kyiv"
      KIOSK_ALBUM: ""
      KIOSK_OPTIMIZE_IMAGES: true
    ports:
      - 2284:3000
    volumes:
      - ./config:/config
      - ./custom.css:/custom.css
    restart: always
```

**custom.css**
```
#clock {
        postition: absolute;
        bottom: 0;
}
```
