### ISSUE TITLE
disable_ui prevents image from ever changing

### ISSUE THREAD

**Issue by genebean** [damongolding/immich-kiosk#263]
**Describe the bug**

While setting this up with two different displays, each on their own album and each with different refresh times, I observed that `disable_ui` as a url parameter caused the images to never change. I determined it was this particular parameter by adjusting my url one param at a time until it started working. After removing `disable_ui` and adding in both `show_time=false` and `show_date=false` instead, everything works fine.

**Expected behavior**

I expect the parameter to work as intended, not disable the refresh.

**Your Kiosk version**

0.14.7

**Your Kiosk installation**

docker

**Your Kiosk ENV or config file**

```yaml
## Required settings - move these to ENV if you want to check in this file
immich_api_key: "redacted"
immich_url: "https://immich.example.com"

## Clock
show_time: true
time_format: 12 # 12 or 24
show_date: true
date_format: MM/DD/YYYY

## Kiosk behaviour
refresh: 60 # in seconds
disable_screensaver: true # Ask browser to request a lock that prevents device screens from dimming or locking.

## Asset sources
show_archived: false # Allow assets marked as archived to be displayed.

## ID(s) of person or people to display
person:
  - "PERSON_ID"

## ID(s) of album or albums to display
album:
  - "ALBUM_ID"
## Album IDs to exclude from being shown. Albums in this list will be filtered from
## appearing in the frame even if they are included in the 'album' list.
excluded_albums:
  - "ALBUM_ID"

## UI
disable_ui: false # this is just a shortcut for all ui elements (show_time, show_date, show_image_time, show_image_date)
frameless: false # remove border around image and rounded corners.
hide_cursor: false # Hide cursor/mouse via CSS.
font_size: 100 # the base font size as a percentage. OMIT the % character
background_blur: true # display a blurred version of image as background
theme: fade # which theme to use. fade or solid
layout: single # which layout to use. single, splitview or splitview-landscape

## Sleep mode
# sleep_start: 22 # sleep mode start time
# sleep_end: 7 # sleep mode end time
sleep_icon: true

## Transition options
transition: none # cross-fade, fade or none
fade_transition_duration: 1 # in seconds
cross_fade_transition_duration: 1 # in seconds

## Image display settings
show_progress: false # display a progress bar
image_fit: contain # Options are none, contain and cover
image_effect: none # Options are none, zoom and smart-zoom
image_effect_amount: 120
use_original_image: false # use the original file.

## Image METADATA
show_album_name: false
show_person_name: false
show_image_time: false
image_time_format: 24 # 12 or 24
show_image_date: false
image_date_format: YYYY-MM-DD
show_image_description: false
show_image_exif: false
show_image_location: false
hide_countries:
  - "country to hide"
show_image_id: false
show_more_info: true
show_more_info_image_link: true
show_more_info_qr_code: true

## Weather feature - you’ll need an API key from OpenWeatherMap
# weather:
#   - name: london
#     lat: 51.5285262
#     lon: -0.2663999
#     api: ""
#     unit: metric
#     lang: en

## Options that can NOT be changed via url params
kiosk:
  port: 3001
  watch_config: false
  fetched_assets_size: 1000
  http_timeout: 20
  password: ""
  cache: true # cache select api calls
  pre_fetch: true # fetch assets in the background
  asset_weighting: true # use weighting when picking assets
  redirects:
    - name: 'kiosk-entryway'
      url: '/?album=<my first album>3&show_time=false&show_date=false&transition=cross-fade&refresh=3600'
      type: internal
    - name: 'kiosk-gene-desk'
      url: '/?album=<my second album>&show_time=false&show_date=false&transition=cross-fade&refresh=300'
      type: internal
```

**Any parms passed to the URL used to access Kiosk**

I tested with the same ones that are in the redirects section of my config after finding that the images were not changing

**Laptop:**
 - OS: NixOS 24.11
 - Browser: Firefox
 - Version 133.0.3

**Kiosk 1**
- OS: MX Linux KDE on an x86_64 Lenovo
- Browser: Chromium
- Version: not sure, current debian though
- Not sure if running Wayland or X, can't check right now, but would guess Wayland.
- Chromium is launched by hand right now

**Kiosk 2**
- OS: NixOS on a Raspberry Pi 4 (64bit)
- Browser: Chromium
- Version: 131.0.6778.264
- Wayland with Cage managing the windows
- Chromium is launched automatically from a script in kiosk mode
