### ISSUE TITLE
Information displayed off screen after latest immich update.

### ISSUE THREAD

**Issue by tehniemer** [damongolding/immich-kiosk#278]
**Describe the bug**
Time and picture location info is displayed off screen, similar to what was happening with the temperature in #255 

**To Reproduce**
Run on old chrome version

**Expected behavior**
The information is displayed on screen

**Screenshots**

![Image](https://github.com/user-attachments/assets/f4c26480-6563-42fe-b694-096f8264d379)

![Image](https://github.com/user-attachments/assets/c85bbe53-2d89-451e-aad0-7e2c800c0407)

**Your Kiosk version**
0.15.1

**Your Kiosk installation**
- Docker

**Your Kiosk ENV or config file**
```
# Required settings
immich_api_key: ""
immich_url: ""

# Clock
show_time: true # true or false
time_format: 12 # 12 or 24
show_date: true # true or false
date_format: MM/DD/YYYY

# Kiosk behaviour
refresh: 60 # in seconds
disable_screensaver: false # Ask browser to request a lock that prevents device screens from dimming or locking.

# Asset sources
show_archived: false # Allow assets marked as archived to be displayed.
person: # ID(s) of person or people to display
  - ""
  - ""
album: # ID(s) of album or albums to display
  - ""

# UI
disable_ui: false # this is just a shortcut for all ui elements (show_time, show_date, show_image_time, show_image_date)
hide_cursor: false # Hide cursor/mouse via CSS.
font_size: 100 # the base font size as a percentage. OMIT the % character
background_blur: true # display a blurred version of image as background
theme: fade # which theme to use. fade or solid
layout: single # which layout to use. single or splitview

# Sleep mode
sleep_start: 1 # sleep mode start time
sleep_end: 5 # sleep mode end time

# Transition options
transition: fade # cross-fade, fade or none
fade_transition_duration: 1 # in seconds
cross_fade_transition_duration: 1 # in seconds

# Image display settings
show_progress: false # display a progress bar
image_fit: contain # how the image fits the screen. Options are none, contain and cover
image_zoom: false # add a zoom effect to images
image_zoom_amount: 120 # The amount zoomed as a percentage

# Image METADATA
show_image_time: false # true or false
image_time_format: 12 # 12 or 24
show_image_date: true # true or false
image_date_format: MM/DD/YYYY
show_image_exif: false
show_image_location: true

# Weather settings
weather:
 - name: 
   lat: 
   lon: 
   api: 
   unit: imperial
   lang: en
   default: true

# options that can NOT be changed via url params
kiosk:
  password: ""
  cache: true # cache select api calls
  pre_fetch: true # fetch assets in the background
  asset_weighting: true # use weighting when picking assets
```

**Any parms passed to the URL used to access Kiosk**
none

**Smartphone:**
 - Device: [e.g. Nexphoto frame]
 - OS: [e.g. Android 4.4.2]
 - Browser [e.g. chrome]
 - Version [e.g. 81.0.4044.138]
