### ISSUE TITLE
Raw Mode HA Background

### ISSUE THREAD

**Issue by janstadt** [damongolding/immich-kiosk#30]
I've set the background of one of my home assistant dashboards to my kiosk instance like this: http://192.168.1.68:3000/image?person=[personid]&raw but the background does not change. It only loads one picture on my dashboards until the entire page refreshes. I tried it like the default way but that didnt display anything: http://192.168.1.68:3000?person=[personid] 

Im using this on a dedicated (always on) Lenovo ThinkSmart device as a nest replacement and was hoping this would shuffle through photos as the background. Unsure whats going on but is it supposed to refresh? I also tried passing in the refresh query param but that didnt work either.

**Comment by janstadt** [comment]
So i was kinda able to get this to work the way i wanted using the [generic camera entity](https://www.home-assistant.io/integrations/generic/) pointing to the raw url and setting the framerate to like .03. This causes it to reload ~30 seconds which is sufficient. You also cant go back or forth and no transitions though but it gets me closer to my goal. Would really love it if there was a better way of getting this to work.

**Comment by damongolding** [comment]
That won’t really be possible unless it was made into a GIF transition from one image to the next but that would be a HUGE file. The k linear to get those kind of features with from the HA side or if the card/element supports html/css.

**Comment by janstadt** [comment]
Understood. The generic camera entity is working for the most part now, but it would be great to expose some form of simple api for the kiosk for previous/next or something and then i think someone would eventually build a native integration for this into HASS.

**Comment by zach-sb** [comment]
If you are just wanting a slideshow in a card I can't help you, but if you're actually going for a fullscreen slideshow, I can highly recommend [wallpanel](https://github.com/j-a-n/lovelace-wallpanel) in HACS. You can actually point it to the raw image that Immich Kiosk provides.

I have a tablet that I have set in a photoframe, and I use wallpanel to start a slideshow after it has been idle for some time. The config looks like this

```
wallpanel:
  enabled: true
  image_fit: cover
  profiles:
    user.living_room_photoframe:
      screensaver_entity: input_boolean.screensaver_lrpf
      screensaver_stop_navigation_path: /lovelace/living-room
      fullscreen: true
      idle_time: 15
      display_time: 120
      image_url: >-
        http://[immich_kiosk]/image?raw&person=[personID]&random=${timestamp}
      cards: []
  badges: null
  cards: []
```

The image_url points to my instance of immich kiosk. One important thing to do if you go this way is to have that `$[timestamp]` value in the url. This forces the url to change on wallpanels end so it will constantly load a new image for each slide, otherwise it would just be stuck on the one image until the page refreshes.

The other thing I suggest if you go this way is give your kiosk device it's own user, that way you can apply a wall panel settings to just that user (in my case ` user.living_room_photoframe`). Also let's you know when something was changed from that specific device in HA logs. ;)
