### ISSUE TITLE
Weather is not being displayed

### ISSUE THREAD

**Issue by stal1n274** [damongolding/immich-kiosk#320]
**Describe the bug**
There is no information about weather in right upper corner.

**To Reproduce**
Here is my config

``` weather:
   - name: Rivne
     lat: 50.62308
     lon: 26.22743
     api: XXX
     unit: metric
     lang: ua, uk 
     default: true
```

**Your Kiosk version**
kiosk-version: 0.17.0

**Your Kiosk installation**
- Docker

**Additional context**
I tried different 'name', different 'lang' but nothing helps. I have no information about the weather.

URL with this api works: https://api.openweathermap.org/data/2.5/weather?q=Rivne,ua&APPID=9f92fc94b4d1d25f6223202f2d4a78b3

Also, there is no weather by using specific URL with parameter to my Kiosk: http://{URL}?weather=Rivne

**Comment by damongolding** [comment]
It's your `lang` field.

```yaml
   - name: Rivne
     lat: 50.62308
     lon: 26.22743
     api: XXX
     unit: metric
     lang: ua
     default: true
```

and 

```yaml
   - name: Rivne
     lat: 50.62308
     lon: 26.22743
     api: XXX
     unit: metric
     lang: uk
     default: true
```

worked for me

**Comment by stal1n274** [comment]
So, should I only change `lang: uk` ? 
I tried without any luck. 

What else can I check?

**Comment by damongolding** [comment]
Yes, try:

```yaml
   - name: Rivne
     lat: 50.62308
     lon: 26.22743
     api: XXX
     unit: metric
     lang: uk
     default: true
```

Then restart the container `docker compose restart`.

If it's still not working check the Kiosk terminal output to see if you have any errors

**Comment by stal1n274** [comment]
Here are my logs from container:

```
Kiosk listening on port 3000

18:39:03 INFO Set default weather location name=Rivne
18:39:13 ERRO Request failed, retrying attempt=0 URL="{Scheme:https Opaque: User: Host:api.openweathermap.org Path:data/2.5/weather RawPath: OmitHost:false ForceQuery:false RawQuery:appid=9f92fc94b4d1d25f6223202f2d4a78b3&lat=50.62308&lon=26.22743&units=metric&lang=uk Fragment: RawFragment:}" err="Get \"https://api.openweathermap.org/data/2.5/weather?appid=9f92fc94b4d1d25f6223202f2d4a78b3&lat=50.62308&lon=26.22743&units=metric&lang=uk\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
18:39:19 ERRO Request failed, retrying attempt=1 URL="{Scheme:https Opaque: User: Host:api.openweathermap.org Path:data/2.5/weather RawPath: OmitHost:false ForceQuery:false RawQuery:appid=9f92fc94b4d1d25f6223202f2d4a78b3&lat=50.62308&lon=26.22743&units=metric&lang=uk Fragment: RawFragment:}" err="Get \"https://api.openweathermap.org/data/2.5/weather?appid=9f92fc94b4d1d25f6223202f2d4a78b3&lat=50.62308&lon=26.22743&units=metric&lang=uk\": dial tcp: lookup api.openweathermap.org on 127.0.0.11:53: server misbehaving"
18:39:31 ERRO Request failed, retrying attempt=2 URL="{Scheme:https Opaque: User: Host:api.openweathermap.org Path:data/2.5/weather RawPath: OmitHost:false ForceQuery:false RawQuery:appid=9f92fc94b4d1d25f6223202f2d4a78b3&lat=50.62308&lon=26.22743&units=metric&lang=uk Fragment: RawFragment:}" err="Get \"https://api.openweathermap.org/data/2.5/weather?appid=9f92fc94b4d1d25f6223202f2d4a78b3&lat=50.62308&lon=26.22743&units=metric&lang=uk\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
18:39:35 ERRO Request failed after retries err="Get \"https://api.openweathermap.org/data/2.5/weather?appid=9f92fc94b4d1d25f6223202f2d4a78b3&lat=50.62308&lon=26.22743&units=metric&lang=uk\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
18:39:35 ERRO Failed to update initial weather name=Rivne error="Get \"https://api.openweathermap.org/data/2.5/weather?appid=9f92fc94b4d1d25f6223202f2d4a78b3&lat=50.62308&lon=26.22743&units=metric&lang=uk\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

**Comment by damongolding** [comment]
Ahh this is a docker network issue. A quick (but not the best) fix is to try adding `network_mode: "host"` to your compose file

Example:

```yaml
services:
  immich-kiosk:
    image: ghcr.io/damongolding/immich-kiosk:latest
    container_name: immich-kiosk
    network_mode: "host"
    /* ... the rest of the file */
```
