### ISSUE TITLE
immich-kiosk-development:0.19.0-beta.{4-6}

### ISSUE THREAD

**Issue by aboulos1229** [damongolding/immich-kiosk#342]
**Describe the bug**
On versions `0.19.0-beta.4`, `beta.5`, and `beta.6 `of `immich-kiosk-development`, some photos occasionally appear upside down. Additionally, videos longer than a few (~5-10) seconds consistently freeze during playback until the kiosk is refreshed or the asset is manually switched.

**To Reproduce**
1. Update server the source to `ghcr.io/damongolding/immich-kiosk-development:0.19.0-beta.`{4-6}.
2. Start the kiosk server.
3. Navigate to the server's URL.
4. Observe assets during playback.

**Expected behavior**
Photos should consistently appear upright. Videos of all lengths should play without freezing.

**Screenshots**
N/A

**Your Kiosk version**
Switched to `ghcr.io/damongolding/immich-kiosk-development:0.19.0-beta.3` as a temporary workaround, which solves these issues.

**Your Kiosk installation**
- Docker

**Your Kiosk config file**
```
# Users
immich_users_api_keys:
  andrew: "<redacted>"
  neama: "<redacted>"
  maddy: "<redacted>"

# Clock
show_time: true
time_format: 12
show_date: true
date_format: DDD, MMM D, YYYY

# Kiosk behaviour
refresh: 12
disable_screensaver: true

# Transition options
transition: cross-fade
cross_fade_transition_duration: 1.2

# Image display settings
show_progress: true
layout: single
image_fit: contain
image_effect: zoom
image_effect_amount: 140
background_blur_amount: 100
experimental_album_video: true
album:
  - ef2980a2-fc1d-4a2d-a9a5-12ddd2a2bd8b
excluded_albums:
  - 4d3d9a27-4c99-414e-a0c3-d54b901e3f80

# Weather feature
weather:
  - name: dallas
    lat: <redacted>
    lon: <redacted>
    api: "<redacted>"
    unit: imperial
    lang: en
    default: true

## Options that can NOT be changed via url params
kiosk:
  watch_config: true
  prefetch: true
  redirects:
    - name: mom
      url: /?font_size=50&album=e274925d-5716-4a05-82e3-9e19e8a265fa&person=774e57b8-eb92-46f9-b9a3-d0c2a0a84c00&person=b1b0b469-3566-4c06-82c7-ef803e275e13&person=4b08b45f-ec5c-4fa8-8e5e-d0401efd9761&person=e3e2dfe1-921c-4f10-809f-4c3e7b2ca22a&person=94df31dd-9f97-4838-ae84-b0064f9f0348&person=aed17839-0d7a-4bc6-8cdc-75a8cc59d8ad&person=48d4a187-3b6e-458b-91fc-1d25bcd555f3&person=098ef6ab-656f-4dec-8653-7db99a3b15da&person=2678acc7-60c4-4975-b5e4-410e2bf5ccb9&person=4aee924e-68a3-4e00-8c55-8796427997dd&person=3c323ccf-c144-4434-9804-00be834f0882&person=6c757390-44fe-46b8-92f8-3fbbc67d6690&person=8087f642-2743-4661-9cb7-728792c98daf&person=6dc6048f-df15-447a-920b-20abcfd21afd&person=2fe260fa-bcad-43ec-881c-0831d5136529&person=95d43e03-180f-45a0-b2f1-5ce1a122193e&person=7312679e-8076-44c9-8d24-0ad6e4dd89d7&person=89a37e4a-6a8b-46b4-9fa0-8b0192aa3221&person=646aa8d0-7458-4968-ae63-78f1af4df978&person=020d3e48-783c-4fa8-985e-ca3af782dd41&person=e38e4253-ff3c-4eff-8cb5-be65c113948a&person=142b8e81-affd-4a43-9c47-ef16714008c6&person=9aca2cb7-2fcf-4aa7-8585-33eb43d3c0f0
    - name: josh
      url: /?font_size=50&album=4a81dd4c-d2e2-47ff-bc43-fd9fb68c4f4c
    - name: frame
      url: /?image_effect=smart-zoom&image_effect_amount=240
    - name: pi
      url: /?font_size=80
    - name: tv
      url: /font_size=50
    - name: maddy
      url: /?user=maddy&album=f3fa645d-489f-43d5-8cb8-83633c8cb4ef&image_effect=smart-zoom&image_effect_amount=240

```

**Any parms passed to the URL used to access Kiosk**
- All included in the config file.

**Desktop:**
- Windows 11: Edge (Beta Version 135.0.3179.11) and Chrome.
  - Hardware: Ryzen 9 5950X, Radeon RX 6700 XT, 128 GB RAM.
- Ubuntu 24.10: Chromium Version 136.0.7052.2.
  - Hardware: Intel Core i7-6500U, Intel HD Graphics 520, 8 GB RAM.

**Smartphone:**
- Fire HD Tab 10: Fully Kiosk Browser, WallPanel, Kiwi, Firefox, Amazon Silk.
- Orange Pi Zero 3: Chromium.

**Additional context**
- The device and/or browser used had no effect on the frequency of frozen videos or upside down photographs.
- Videos:
  - Short videos (≤10 seconds) more often freeze at the cross-fade transition point.
  - Longer videos (~≥10 seconds) freeze approximately halfway through playback.
- Photos: Rarely, some photos display upside down, though they appear correct when viewed in Immich.
