### ISSUE TITLE
Archived photos from albums do not show

### ISSUE THREAD

**Issue by lukaszwawrzyk** [damongolding/immich-kiosk#345]
**Describe the bug**
I tend to archive most of my photos that are in albums, to keep my timeline cleaner, I just leave some of them unarchived. I have archive enabled and I want to show all albums except disabled ones. However it seems, that I only see photos that are in albums and in timeline at the same time, i.e. I don't see photos from albums that are archived.

**To Reproduce**
Use my configuration.
Have album with some of its photos archived
Never see these photos in kiosk.

**Expected behavior**
Show all photos from all allowed albums, including photos that are archived

**Your Kiosk version**
0.18.0

**Your Kiosk installation**
- Docker

**Your Kiosk ENV or config file**
```
  immich-kiosk:
    image: ghcr.io/damongolding/immich-kiosk:latest
    container_name: immich-kiosk
    environment:
      LANG: "pl_PL"
      TZ: "Europe/Warsaw"
      # Required settings
      KIOSK_IMMICH_API_KEY: "XXX"
      KIOSK_IMMICH_URL: "http://immich-server:2283"
      # Clock
      KIOSK_SHOW_TIME: false
      KIOSK_TIME_FORMAT: 24
      KIOSK_SHOW_DATE: false
      KIOSK_DATE_FORMAT: DD-MM-YYYY
      # Kiosk behaviour
      KIOSK_REFRESH: 60
      KIOSK_DISABLE_SCREENSAVER: false
      # Asset sources
      KIOSK_SHOW_ARCHIVED: true
      KIOSK_ALBUM: "all"
      KIOSK_EXCLUDED_ALBUMS: "87d51560-257e-4f2f-9ec5-2cf9d221088e,76d5f521-a3f3-4ea6-b743-2473ee6d9db1,331b31b2-6957-40a9-a67f-72ef2189b26e,7d8b0969-e194-4142-a020-393e4b58a5e7,882bcb0b-c4b0-4549-89d6-3dd8d6c7707e,c831b178-4087-4222-b699-d53fd93adb39,5fdb67f9-f061-4ce1-8aea-4213e31ceb08,fa0ba8c8-1eec-4d83-a96c-9eed41a481b4,6d39a1f6-e483-4fd3-b55e-dafd0c28f79b,a231ee29-60e9-4984-a822-17235c3a0b2c,1847c9d4-5deb-48e0-a77c-98a5f545a61d,07fda5fc-acf5-49f1-8963-f2339ab62ad4,200ee89f-3588-4d58-b3a9-aa9250c78b4b,1426200c-dfb6-443b-910f-92093fd9d8c9,1d158fbf-516f-403e-8fec-fb1b75cb7296,48b58249-27b1-4bb2-90dc-76af11e30772,cc5c1ac3-3063-48b7-a9fc-c70893e41551,089feb3c-afcc-4bd8-adfa-1ab3971b94d0,bedc3b56-660c-4703-9d97-2a87d58a6f19,cd93b656-523e-4f92-8eb4-3478944315e1,4e5211d9-fad8-4a01-99c1-9653b8fdb777,06e963df-e17b-439c-98dc-1398bfb2ecce,bc22bb1f-cdaf-4ead-bd38-7845d116274e,f186bdcc-1c1f-467c-8316-aedefc9cf467,392a7d0a-0893-4cba-bffa-f36c132980c2,6ffb8d28-a63c-4085-926e-621b7d0b5ba0,"
      #KIOSK_PERSON: "PERSON_ID,PERSON_ID,PERSON_ID"
      # UI
      KIOSK_DISABLE_UI: false
      KIOSK_FRAMELESS: true
      KIOSK_HIDE_CURSOR: false
      KIOSK_FONT_SIZE: 100
      KIOSK_BACKGROUND_BLUR: true
      KIOSK_THEME: fade
      KIOSK_LAYOUT: splitview
      # Sleep mode
      KIOSK_SLEEP_START: 1
      KIOSK_SLEEP_END: 7
      # Transistion options
      KIOSK_TRANSITION: cross-fade
      KIOSK_FADE_TRANSITION_DURATION: 3
      KIOSK_CROSS_FADE_TRANSITION_DURATION: 3
      # Image display settings
      KIOSK_SHOW_PROGRESS: false
      KIOSK_IMAGE_FIT: contain
      KIOSK_IMAGE_EFFECT: smart-zoom
      KIOSK_IMAGE_EFFECT_AMOUNT: 300
      KIOSK_USE_ORIGINAL_IMAGE: false
      # Image metadata
      KIOSK_SHOW_ALBUM_NAME: true
      KIOSK_SHOW_IMAGE_TIME: true
      KIOSK_IMAGE_TIME_FORMAT: 24
      KIOSK_SHOW_IMAGE_DATE: true
      KIOSK_IMAGE_DATE_FORMAT: DD-MM-YYYY
      KIOSK_SHOW_IMAGE_DESCRIPTION: false
      KIOSK_SHOW_IMAGE_EXIF: false
      KIOSK_SHOW_IMAGE_LOCATION: false
      KIOSK_HIDE_COUNTRIES: "Poland"
      KIOSK_SHOW_IMAGE_ID: false
      # Kiosk settings
      KIOSK_WATCH_CONFIG: false
      KIOSK_FETCHED_ASSETS_SIZE: 1000
      KIOSK_HTTP_TIMEOUT: 20
      KIOSK_PASSWORD: ""
      KIOSK_CACHE: true
      KIOSK_PREFETCH: true
      KIOSK_ASSET_WEIGHTING: true
      KIOSK_PORT: 6496
```

**Any parms passed to the URL used to access Kiosk**
- no params
