### ISSUE TITLE
Unable to alter images via "more info" UI

### ISSUE THREAD

**Issue by j-inc** [damongolding/immich-kiosk#357]
**Describe the bug**
Pressing the like or hide buttons fails. Here is the error:
```
14:39:20 ERRO unexpected status code: 404
14:39:20 ERRO Failed to add tag to asset error="unexpected status code: 404"
14:39:20 ERRO Couldn't read error body="" url=http://img.app.domain.tld/api/tags/XXXXXXXX-6a00-41e2-b5d6-1b0c57191b80/assets
14:39:20 ERRO  PzRGFTirQgKqicmtiyxziSJPhyRZAXBf  error adding tag to asset assetID=XXXXXXXX-7d32-4017-91ef-f0da387a8a44 error="unexpected end of JSON input"
```
(I added the XXXXs to asset UUIDs)

**To Reproduce**
Enter kiosk, press more info on image, press either button.

**Expected behavior**
The tag to be added when the hide button is pressed.

**Your Kiosk version**
0.19

**Your Kiosk installation**
- Docker, in Debian VM, on Proxmox. Assets are within NFS share, but contained within the same Portainer stack as Immich so there should be no permissions issues.

**Your Kiosk ENV or config file**
```
## Required settings - move these to ENV if you want to check in this file
immich_api_key: "
immich_url: "
immich_external_url: "
## Clock
show_time: true
time_format: 12 # 12 or 24
show_date: true
date_format: YYYY/MM/DD 

## Kiosk behaviour
refresh: 30 # in seconds
disable_screensaver: false # Ask browser to request a lock that prevents device screens from dimming or locking.
optimize_images: true # Whether Kiosk should resize images to match your browser screen dimensions for better performance.
use_gpu: true # Enable GPU acceleration for improved performance.

## Asset sources
show_archived: false # Allow assets marked as archived to be displayed.

## ID(s) of person or people to display
person:
#   - "PERSON_ID"

## ID(s) of album or albums to display
album:
  -
  -
  -
  
## Album IDs to exclude from being shown. Albums in this list will be filtered from
## appearing in the frame even if they are included in the 'album' list.
album_order: random # random | newest | oldest
excluded_albums:
  - 

## Date range or ranges to display
date:
#   - "YYYY-MM-DD_to_YYYY-MM-DD"

## Value(s) of tag(s) to display
tag:
#   - "TAG_VALUE"

memories: false # show memories

## Filters
# date_filter: last-30-days # only applies to people and random assets

## Experimental
experimental_album_video: false

## UI
disable_ui: false # this is just a shortcut for all ui elements (show_time, show_date, show_image_time, show_image_date)
frameless: false # remove border around image and rounded corners.
hide_cursor: false # Hide cursor/mouse via CSS.
font_size: 100 # the base font size as a percentage. OMIT the % character
background_blur: true # display a blurred version of image as background
background_blur_amount: 10 # amount of blur to apply to background image (sigma)
theme: fade # which theme to use. fade or solid
layout: single # which layout to use. single | splitview | splitview-landscape | portrait | landscape

## Sleep mode
sleep_start: 23 # sleep mode start time
sleep_end: 7 # sleep mode end time
sleep_icon: false

## Transition options
transition: fade # cross-fade, fade or none
fade_transition_duration: 1 # in seconds
cross_fade_transition_duration: 1 # in seconds

## Image display settings
show_progress: false # display a progress bar
image_fit: contain # none | contain | cover
image_effect: none # none | zoom | smart-zoom
image_effect_amount: 0
use_original_image: false # use the original file.

## Image METADATA
show_album_name: true
show_person_name: false
show_image_time: false
image_time_format: 24 # 12 or 24
show_image_date: true
image_date_format: YYYY-MM-DD
show_image_description: true
show_image_exif: false
show_image_location: true
hide_countries:
  - "country to hide"
show_image_id: false
show_more_info: true
show_more_info_image_link: true
show_more_info_qr_code: true

hide_button_action: tag

## Options that can NOT be changed via url params
kiosk:
  port: 3000
  watch_config: true
  fetched_assets_size: 1000
  http_timeout: 20
  password: ""
  cache: true # cache select api calls
  pre_fetch: true # fetch assets in the background
  asset_weighting: true # use weighting when picking assets
```

**Any parms passed to the URL used to access Kiosk**
- http://****/?font_size=200&hide_cursor=true

Error happens on all clients. I am using a touchscreen display for the primary kiosk, which otherwise works fine.

**Additional context**

**On an unrelated note, I have a tiny feature request for this excellent project: could you have the QR codes scale with font size? I am using a 3840x2400 display for the main kiosk and using a 200 font size makes the QR code teeny tiny. It is only a 13.4" monitor.**
