### ISSUE TITLE
Getting videos in my random rotation?

### ISSUE THREAD

**Issue by steveredden** [damongolding/immich-kiosk#379]
I appear to be getting videos in my random loop.

I'll be adding `experimental_album_video: false` just in case, but this should be the default, no?

Config as so:

```yaml
immich_api_key: secretttttt
immich_url: https://immich.my.tld
show_progress: false # display a progress bar
refresh: 8 # in seconds
album: "" # ID of album to display
experimental_album_video: false
person: # ID(s) of person or people to display
  - b9b23ab6-b04d-4cab-bc40-43de86e6007c
  - 548d6b1b-fce1-4ee5-a7d3-22466c5a12e5
blacklist:
  - 4c5b47c5-1fa3-436b-905e-75b97fc4361f
  - 5d01fb5a-d394-42fc-8487-119d1e72967e
  - 01e48aa3-a082-46c6-bdab-6d6254131140
image_fit: contain # how the image fits the screen. Options are none, contain and cover
background_blur: true # display a blurred version of image as background
transition: cross-fade # cross-fade, fade or none

disable_ui: false # this is just a shortcut for all ui elements (show_time, show_date, show_image_time, show_image_date)

# Clock Display
show_time: false # true or false
time_format: 12 # 12 or 24
show_date: false # true or false
date_format: 01/02/2006 # 02 = day, 01 = month and 2006 = year e.g. 01/02/2006 for American format

# Image Dateteime Display
show_image_date: true # true or false
image_date_format: 01/02/2006 # 02 = day, 01 = month and 2006 = year e.g. 01/02/2006 for American formate
show_image_time: false # true or false
image_time_format: 12 # 12 or 24

# options that can not be changed via url params
kiosk:
  password: ""
```

**Comment by damongolding** [comment]
It should be turned off by default yes. Unless you have it turned on via env or the url?

**Comment by steveredden** [comment]
i haven't gotten any videos since including the `experimental_album_video: false` declaration in my config.  Probably some weird interaction with me omitting an `album` entirely, yet specifying `person`s.  I didn't look at the codepath, but i think my issue is solved.

**Comment by damongolding** [comment]
Really odd behaviour. It should be false by default. I'll run some tests when i get a moment just to be sure.

**Comment by steveredden** [comment]
I think I figured out what was happening to me.  

I was using home assistant wallpanel in a dashboard:

```yaml
wallpanel:
  enabled: true
  image_fit: contain
  image_list_update_interval: 9
  display_time: 10
  image_order: random
  image_background: image
  image_url: https://immich-kiosk.vicariouslyliving.com/image?raw&entropy=${timestamp}
```

Switching `image_url` from

```yaml
image_url: https://immich-kiosk.vicariouslyliving.com/image?raw&entropy=${timestamp}
```

to

```yaml
image_url: https://immich-kiosk.vicariouslyliving.com/image?entropy=${timestamp}
```

seems to have fixed my issue.  I forget why i had `raw` as a query parameter.... and I don't see it in your docs anymore...

Thanks for humoring me.
