### ISSUE TITLE
Some assets upside down

### ISSUE THREAD

**Issue by nothing2obvi** [damongolding/immich-kiosk#391]
**Describe the bug**
Some assets are upside-down, but not upside-down within Immich itself.

**To Reproduce**
1. Set up album
2. View in Immich Kiosk
3. Some assets are upside down.

**Expected behavior**
An asset is right-side-up unless actually upside-down in Immich.

**Your Kiosk version**
0.20.2

**Your Kiosk installation**
- Docker

**Your Kiosk ENV or config file**
```
## Required settings - move these to ENV if you want to check in this file
immich_api_key: "key-here"
immich_url: "url-here"

## Clock
show_time: true
time_format: 12 # 12 or 24
show_date: true
date_format: YYYY/MM/DD
clock_source: client 

## Kiosk behaviour
refresh: 60 # in seconds
disable_screensaver: false # Ask browser to request a lock that prevents device screens from dimming or locking.
optimize_images: false # Whether Kiosk should resize images to match your browser screen dimensions for better performance.
use_gpu: true # Enable GPU acceleration for improved performance.

## Asset sources
show_archived: false # Allow assets marked as archived to be displayed.

## ID(s) of person or people to display
person:
  #- "c4622ee0-a64b-4112-956f-86a247889e49" # Mom
  #- "f2113274-5c9d-46da-9cc5-4d705f4dd8f0" # Dad
excluded_people:
  

## ID(s) of album or albums to display
album:
  - "d494e609-0886-4e0c-a18a-96bd29db9e94"
## Album IDs to exclude from being shown. Albums in this list will be filtered from
## appearing in the frame even if they are included in the 'album' list.
album_order: random # random | newest | oldest
#excluded_albums:
  #- "ALBUM_ID"

## Date range or ranges to display
#date:
  #- "YYYY-MM-DD_to_YYYY-MM-DD"

## Value(s) of tag(s) to display
#tag:
  #- "TAG_VALUE"

memories: false # show memories

## Blacklist

blacklist: 9bd01f0d-3912-44d4-9218-fab3deb65637

## Filters
# date_filter: last-30-days # only applies to people and random assets

## Experimental
experimental_album_video: false

## UI
disable_ui: false # this is just a shortcut for all ui elements (show_time, show_date, show_image_time, show_image_date)
frameless: false # remove border around image and rounded corners.
hide_cursor: true # Hide cursor/mouse via CSS.
font_size: 100 # the base font size as a percentage. OMIT the % character
background_blur: true # display a blurred version of image as background
background_blur_amount: 10 # amount of blur to apply to background image (sigma)
theme: fade # which theme to use. fade or solid
layout: splitview # which layout to use. single | splitview | splitview-landscape | portrait | landscape

## Sleep mode
sleep_start: 1 # sleep mode start time
sleep_end: 7 # sleep mode end time
sleep_icon: true

## Transition options
transition: none # cross-fade, fade or none
fade_transition_duration: 1 # in seconds
cross_fade_transition_duration: 1 # in seconds

## Image display settings
show_progress: false # display a progress bar
image_fit: contain # none | contain | cover
image_effect: none # none | zoom | smart-zoom
image_effect_amount: 120
use_original_image: true # use the original file.

## Image METADATA
show_album_name: false
show_person_name: false
show_person_age: false
show_image_time: false
image_time_format: 24 # 12 or 24
show_image_date: false
image_date_format: YYYY-MM-DD
show_image_description: false
show_image_exif: false
show_image_location: false
hide_countries:
  - "country to hide"
show_image_id: false
show_more_info: true
show_more_info_image_link: true
show_more_info_qr_code: true

like_button_action: [favorite, album] # album, favorite or both [album, favorite]
hide_button_action: tag # tag, archive, or both [tag, archive]

## Weather feature - you’ll need an API key from OpenWeatherMap
weather:
  - name: location-here
    lat: lat-here
    #lat: 38.0471158
    lon: lon-here
    #lon: -121.9767815
    api: "api-here"
    unit: imperial
    lang: en
    default: true

## Immich API keys for specific users
# immich_users_api_keys:
#   user1: ""
# show_user: false # show user name

## Options that can NOT be changed via url params
kiosk:
  port: 3000
  watch_config: false
  fetched_assets_size: 1000
  http_timeout: 20
  password: "password-here"
  cache: true # cache select api calls
  pre_fetch: true # fetch assets in the background
  asset_weighting: true # use weighting when picking assets
```

**Any parms passed to the URL used to access Kiosk**
- http://****/?password=PASSWORD

**Desktop:**
 - OS: MacOS 15.3
 - Browser: Opera
 - Version: 118.0.5461.60

**Kiosk Device:**
 - Device: Raspberry Pi Zero 2 W
 - OS: DietPi 9.12.1
 - Browser: Chromium
 - Chromium Version: Latest stable; checking version shows "It is not recommended to run Chromium on devices with less than 1GB of RAM."
