### ISSUE TITLE
image/reload endpoint not loading images

### ISSUE THREAD

**Issue by aka-charos** [damongolding/immich-kiosk#413]
**Describe the bug**
The newly introduced image/reload endpoint doesn't seem to load any image

**To Reproduce**
1. Go to  (mysite.com/image/reload/?password=mypassword)
2. JSON message "unable to retrieve image"
3. Docker logs show  ERRO unexpected status code: 400
4. standard endpoint (mysite.com/?password=mypassword) works fine.

**Expected behavior**
Image is loaded (and reloaded obviously)

**Your Kiosk version**
Version 0.21.0

**Your Kiosk installation**
 Docker

**Your Kiosk ENV or config file**
```
## Clock
show_time: false
time_format: 24 # 12 or 24
show_date: false
date_format: YYYY/MM/DD
clock_source: client

## Kiosk behaviour
refresh: 60 # in seconds
disable_screensaver: false # Ask browser to request a lock that prevents device screens from dimming or locking.
optimize_images: false # Whether Kiosk should resize images to match your browser screen dimensions for better performance.
use_gpu: true # Enable GPU acceleration for improved performance.

## Asset sources
show_archived: false # Allow assets marked as archived to be displayed.

## ID(s) of person or people to display
person:
  - "PERSON_ID"
excluded_people:
  - "PERSON_ID"

## ID(s) of album or albums to display
album:
  - "ALBUM_ID"
## Album IDs to exclude from being shown. Albums in this list will be filtered from
## appearing in the frame even if they are included in the 'album' list.
album_order: newest # random | newest | oldest
excluded_albums:
  - "ALBUM_ID"

## Date range or ranges to display
date:
  - "YYYY-MM-DD_to_YYYY-MM-DD"

## Value(s) of tag(s) to display
tag:
  - "TAG_VALUE"

memories: false # show memories

## Filters
# date_filter: last-30-days # only applies to people and random assets

## Experimental
experimental_album_video: false

## UI
disable_ui: false # this is just a shortcut for all ui elements (show_time, show_date, show_image_time, show_image_date)
frameless: false # remove border around image and rounded corners.
hide_cursor: false # Hide cursor/mouse via CSS.
font_size: 100 # the base font size as a percentage. OMIT the % character
background_blur: true # display a blurred version of image as background
background_blur_amount: 10 # amount of blur to apply to background image (sigma)
theme: fade # which theme to use. fade or solid
layout: single # which layout to use. single | splitview | splitview-landscape | portrait | landscape

## Sleep mode
# sleep_start: 22 # sleep mode start time
# sleep_end: 7 # sleep mode end time
sleep_icon: true

## Transition options
transition: fade # cross-fade, fade or none
fade_transition_duration: 1 # in seconds
cross_fade_transition_duration: 1 # in seconds

## Image display settings
show_progress: false # display a progress bar
image_fit: contain # none | contain | cover
image_effect: none # none | zoom | smart-zoom
image_effect_amount: 120
use_original_image: false # use the original file.

## Image METADATA
show_album_name: false
show_person_name: true
show_image_time: false
image_time_format: 24 # 12 or 24
show_image_date: true
image_date_format: YYYY-MM-DD
show_image_description: true
show_image_exif: false
show_image_location: true
hide_countries:
  - "country to hide"
show_image_id: false
show_more_info: true
show_more_info_image_link: true
show_more_info_qr_code: true

like_button_action: favorite # album, favorite or both [album, favorite]
hide_button_action: tag # tag, archive, or both [tag, archive]

## Weather feature - you’ll need an API key from OpenWeatherMap
# weather:
#   - name: london
#     lat: 51.5285262
#     lon: -0.2663999
#     api: ""
#     unit: metric
#     lang: en

## Immich API keys for specific users
# immich_users_api_keys:
#   user1: ""
# show_user: false # show user name

## Options that can NOT be changed via url params
kiosk:
  port: 3000
  watch_config: false
  fetched_assets_size: 2000
  http_timeout: 20
  password: "<mypassword>"
  cache: true # cache select api calls
  pre_fetch: true # fetch assets in the background
  asset_weighting: true # use weighting when picking assets

```

**Desktop:**
 - OS: Windows 11
 - All browsers
