### ISSUE TITLE
Immich Kiosk stops retrying on startup if immich server is unavailable

### ISSUE THREAD

**Issue by radh21301** [damongolding/immich-kiosk#434]
**Describe the bug**
I'm running into an issue where the Immich Kiosk component starts **before** the main Immich server.

- The image `refresh interval` is set to **1 hour**. [Note: I also tried with a refresh of 10 mins, and observed the same behavior]
- When the kiosk starts and the server isn't available yet, it tries to connect 3 times within a few seconds.
- After those attempts, it stops retrying completely.

I see this on the client device (frameo)
![Image](https://github.com/user-attachments/assets/0686d2af-14b3-4ac4-88cb-81a8684b2fc2)

Here are the relevant logs:

```
20:19:53 ERRO Request failed attempt=0 URL=http://10.20.1.143:1111/api/people/12345678-1234-1234-1234-123456789abc/statistics error_type=*url.Error error="Get \"http://10.20.1.143:1111/api/people/12345678-1234-1234-1234-123456789abc/statistics\": dial tcp 10.20.1.143:1111: connect: connection refused"
20:19:54 ERRO Request failed attempt=1 URL=http://10.20.1.143:1111/api/people/12345678-1234-1234-1234-123456789abc/statistics error_type=*url.Error error="Get \"http://10.20.1.143:1111/api/people/12345678-1234-1234-1234-123456789abc/statistics\": dial tcp 10.20.1.143:1111: connect: connection refused"
20:19:56 ERRO Request failed attempt=2 URL=http://10.20.1.143:1111/api/people/12345678-1234-1234-1234-123456789abc/statistics error_type=*url.Error error="Get \"http://10.20.1.143:1111/api/people/12345678-1234-1234-1234-123456789abc/statistics\": dial tcp 10.20.1.143:1111: connect: connection refused"
20:20:00 ERRO request failed: max retries exceeded. last err=Get "http://10.20.1.143:1111/api/people/12345678-1234-1234-1234-123456789abc/statistics";: dial tcp 10.20.1.143:1111: connect: connection refused
20:20:00 ERRO Couldn't read error body="" url=http://10.20.1.143:1111/api/people/12345678-1234-1234-1234-123456789abc/statistics
20:20:00 ERRO retrieving asset err="selecting asset: getting person image count: request failed: max retries exceeded. last err=Get \"http://10.20.1.143:1111/api/people/12345678-1234-1234-1234-123456789abc/statistics\": dial tcp 10.20.1.143:1111: connect: connection refused"
```

After this, the kiosk remains idle and doesn't attempt to reconnect until the refresh interval hits (1 hour later). Once the 1 hour passes, the kiosk resumes updates as expected (nothing in the logs. But pics start updating). But waiting an hour for a retry seems a bit too long, especially in cases where the kiosk might often come online before the server.

**To Reproduce**
1. Start immich kiosk first
2. Wait about 10 seconds
3. Start immich server
4. You will see the error as shown above. The error would go away when the timer reaches the refresh interval you have in your config.

**Expected behavior**
I suppose Kiosk should try to reconnect more frequently. If someone sets a short refresh interval like 2 minutes, a temporary connection issue wouldn’t be very noticeable. But for those who prefer a longer interval—like an hour—seeing an error screen for that entire time isn’t ideal.

**Screenshots**

**Your Kiosk version**
0.21.2-beta.1-DEVELOPMENT

**Your Kiosk installation**
- Docker

**Your Kiosk ENV or config file**
```
## Required settings - move these to ENV if you want to check in this file
immich_api_key: "aaaaaa"
immich_url: "http://immich-ip:port"

## Clock
show_time: true
time_format: 12 # 12 or 24
show_date: false
date_format: YYYY/MM/DD
clock_source: client

## Kiosk behaviour
refresh: 3600 # in seconds
disable_screensaver: false # Ask browser to request a lock that prevents device screens from dimming or locking.
optimize_images: true # Whether Kiosk should resize images to match your browser screen dimensions for better performance.
use_gpu: true # Enable GPU acceleration for improved performance.

## Asset sources
show_archived: false # Allow assets marked as archived to be displayed.

## ID(s) of person or people to display
person:
  - "xxx"
  - "yyy"
# excluded_people:
#   - "PERSON_ID"
require_all_people: true
excluded_people:
  - "PERSON_ID"
## ID(s) of album or albums to display
album:
  - "ALBUM_ID"
## Album IDs to exclude from being shown. Albums in this list will be filtered from
## appearing in the frame even if they are included in the 'album' list.
album_order: random # random | newest | oldest
excluded_albums:
  - "ALBUM_ID"

## Date range or ranges to display
date:
  - "YYYY-MM-DD_to_YYYY-MM-DD"

## Value(s) of tag(s) to display
tag:
  - "TAG_VALUE"

memories: false # show memories

## Filters
# date_filter: last-30-days # only applies to people and random assets

## Experimental
experimental_album_video: false

## UI
disable_ui: false # this is just a shortcut for all ui elements (show_time, show_date, show_image_time, show_image_date)
frameless: false # remove border around image and rounded corners.
hide_cursor: false # Hide cursor/mouse via CSS.
font_size: 100 # the base font size as a percentage. OMIT the % character
background_blur: true # display a blurred version of image as background
background_blur_amount: 30 # amount of blur to apply to background image (sigma)
theme: fade # which theme to use. fade or solid
layout: single # which layout to use. single | splitview | splitview-landscape | portrait | landscape

## Sleep mode
# sleep_start: 22 # sleep mode start time
# sleep_end: 7 # sleep mode end time
# sleep_dim_screen: false # dim screen when sleep mode is active (only works with Fully Kiosk Browser)
sleep_icon: true

## Transition options
transition: none # cross-fade, fade or none
fade_transition_duration: 1 # in seconds
cross_fade_transition_duration: 1 # in seconds

## Image display settings
show_progress: false # display a progress bar
image_fit: contain # none | contain | cover
image_effect: smart-zoom # none | zoom | smart-zoom
image_effect_amount: 100
use_original_image: true # use the original file.

## Image METADATA
show_owner: false # show the owner of the image
show_album_name: false
show_person_name: false
show_person_age: false
show_image_time: false
image_time_format: 12 # 12 or 24
show_image_date: false
image_date_format: YYYY-MM-DD
show_image_description: false
show_image_exif: false
show_image_location: false
show_image_qr: false
hide_countries:
  - "country to hide"
show_image_id: false
show_more_info: true
show_more_info_image_link: true
show_more_info_qr_code: true

like_button_action: favorite # album, favorite or both [album, favorite]
hide_button_action: tag # tag, archive, or both [tag, archive]

## Weather feature - you’ll need an API key from OpenWeatherMap
# weather:
#   - name: london
#     lat: 51.5285262
#     lon: -0.2663999
#     api: ""
#     unit: metric
#     lang: en
#     default: false

# show_user: false # show user name

## Offline mode
use_offline_mode: false
offline_mode:
  enabled: true
  number_of_assets: 100
  max_size: 50mb
  parallel_downloads: 4
  expiration_hours: 100
## Options that can NOT be changed via url params
kiosk:
  port: 3000
  watch_config: true
  fetched_assets_size: 1000
  http_timeout: 60
  password: ""
  cache: true # cache select api calls
  prefetch: true # fetch assets in the background
  asset_weighting: true # use weighting when picking assets
```

**Any parms passed to the URL used to access Kiosk**

**Desktop:**

**Smartphone:**
 - Device: Frameo
 - OS: Android
 - Browser: I am not sure. I updated webview to 106 using Rob's (immich frame dev) guide

**Additional context**
