### ISSUE TITLE
404 error for file assets/css/kiosk.0.21.4.css and assets/js/kiosk.0.21.4.js on arm64 binary

### ISSUE THREAD

**Issue by MeTheFlea** [damongolding/immich-kiosk#449]
**Describe the bug**
Starting from `v0.21.1`, I am getting a 404 error for the css and js files mentioned in the title. `v0.21.0` works fine (as well as older versions).

**To Reproduce**
1. Download and deploy `immich-kiosk_Linux_arm64.tar.gz` from `v0.21.1` onwards.
2. See that the immich kiosk page renders with errors.

I normally use the new offline_mode but this happens without offline_mode too.

**Screenshots**

![Image](https://github.com/user-attachments/assets/4547ec82-0ceb-4411-a18b-80744d418e72)

![Image](https://github.com/user-attachments/assets/63033ece-7894-4a83-9902-87dd60dfec61)

**Your Kiosk version**
v0.21.4

**Your Kiosk installation**
- Binary

**Your Kiosk ENV or config file**
```
## Required settings - move these to ENV if you want to check in this file
immich_api_key: XXX
immich_url: XXX

## Clock
show_time: false
time_format: 24 # 12 or 24
show_date: false
date_format: YYYY/MM/DD

## Kiosk behaviour
refresh: 3600 # in seconds
disable_screensaver: true # Ask browser to request a lock that prevents device screens from dimming or locking.
optimize_images: false # Whether Kiosk should resize images to match your browser screen dimensions for better performance.
use_gpu: true # Enable GPU acceleration for improved performance.

offline_mode:
  enabled: true
  number_of_assets: 10
  expiration_hours: 4

## Asset sources
show_archived: false # Allow assets marked as archived to be displayed.

## ID(s) of person or people to display
person:
  - "PERSON_ID"

## ID(s) of album or albums to display
album:
  - "XXX"
## Album IDs to exclude from being shown. Albums in this list will be filtered from
## appearing in the frame even if they are included in the 'album' list.
album_order: random # random | newest | oldest
excluded_albums:
  - "ALBUM_ID"

## Date range or ranges to display
date:
  - "YYYY-MM-DD_to_YYYY-MM-DD"

## Value(s) of tag(s) to display
tag:
  - "TAG_VALUE"

memories: false # show memories

## Filters
# date_filter: last-30-days # only applies to people and random assets

## Experimental
experimental_album_video: false

## UI
disable_ui: false # this is just a shortcut for all ui elements (show_time, show_date, show_image_time, show_image_date)
frameless: false # remove border around image and rounded corners.
hide_cursor: false # Hide cursor/mouse via CSS.
font_size: 100 # the base font size as a percentage. OMIT the % character
background_blur: true # display a blurred version of image as background
background_blur_amount: 10 # amount of blur to apply to background image (sigma)
theme: fade # which theme to use. fade or solid
layout: splitview # which layout to use. single | splitview | splitview-landscape | portrait | landscape

## Sleep mode
# sleep_start: 22 # sleep mode start time
# sleep_end: 7 # sleep mode end time
sleep_icon: true

## Transition options
transition: none # cross-fade, fade or none
fade_transition_duration: 1 # in seconds
cross_fade_transition_duration: 1 # in seconds

## Image display settings
show_progress: false # display a progress bar
image_fit: contain # none | contain | cover
image_effect: none # none | zoom | smart-zoom
image_effect_amount: 120
use_original_image: false # use the original file.

## Image METADATA
show_album_name: false
show_person_name: false
show_image_time: false
image_time_format: 24 # 12 or 24
show_image_date: true
image_date_format: YYYY-MM-DD
show_image_description: false
show_image_exif: false
show_image_location: false
hide_countries:
  - "country to hide"
show_image_id: false
show_more_info: false
show_more_info_image_link: true
show_more_info_qr_code: true

## Weather feature - you’ll need an API key from OpenWeatherMap
# weather:
#   - name: london
#     lat: 51.5285262
#     lon: -0.2663999
#     api: ""
#     unit: metric
#     lang: en

## Immich API keys for specific users
# immich_users_api_keys:
#   user1: ""
# show_user: false # show user name

## Options that can NOT be changed via url params
kiosk:
  port: 3000
  watch_config: false
  fetched_assets_size: 1000
  http_timeout: 30
  password: ""
  cache: true # cache select api calls
  pre_fetch: true # fetch assets in the background
  asset_weighting: true # use weighting when picking assets
```

**Any parms passed to the URL used to access Kiosk**
- http://****/?use_offline_mode=true
- http://****/

**Desktop:**
 - OS: Any
 - Browser: Any
