### ISSUE TITLE
KIOSK_IMAGE_DATE_FORMAT has no effect

### ISSUE THREAD

**Issue by stibbzy** [damongolding/immich-kiosk#46]
For some reason, setting KIOSK_IMAGE_DATE_FORMAT in the environment file doesn't seem to have any effect on the displayed image date. It always retains the default format of YYYY-MM-DD.

Making an identical change KIOSK_DATE_FORMAT has the expected result for all combinations of year, month and day. 

The issue remains after a reboot and in a different browser. Am I missing something?

**Comment by damongolding** [comment]
That doesn't sound right.

Could you supply the version of Kiosk you are running, this can be found on the Kiosk startup log in the terminal or in a META tag or console in the browser. And your compose settings (minus any sensitive data)

**Comment by stibbzy** [comment]
Hi, sorry for the delay. Here is my compose settings:
```
services:
  immich-kiosk:
    image: damongolding/immich-kiosk:latest
    container_name: immich-kiosk
    environment:
      TZ: "Australia/Sydney"
      KIOSK_IMMICH_API_KEY: "xxxxxxxxx"
      KIOSK_IMMICH_URL: "xxxxxxx:2283"
      KIOSK_DISABLE_UI: FALSE
      KIOSK_SHOW_DATE: TRUE
      KIOSK_DATE_FORMAT: DDDD DD MMMM YY
      KIOSK_SHOW_TIME: TRUE
      KIOSK_TIME_FORMAT: 12
      KIOSK_REFRESH: 120
      KIOSK_ALBUM: ""
      KIOSK_PERSON: ""
      KIOSK_IMAGE_FIT: CONTAIN
      KIOSK_BACKGROUND_BLUR: TRUE
      KIOSK_TRANSITION: NONE
      KIOSK_SHOW_PROGRESS: TRUE
      KIOSK_SHOW_IMAGE_TIME: TRUE
      KIOSK_IMAGE_TIME_FORMAT: 12
      KIOSK_SHOW_IMAGE_DATE: TRUE
      KIOSK_IMAGE_DATE_FORMAT: MMM YY
      KIOSK_PASSWORD: ""
      KIOSK_CACHE: TRUE
    ports:
      - 3000:3000
    restart: on-failure
``` 

My Immich-kioskn version is 0.6.0.

Incidentally, I've also noticed that it is not honouring my 120s refresh time either, it's still changing every 60s....
