### ISSUE TITLE
Problem when casting to Google Nest

### ISSUE THREAD

**Issue by carlosjfcasero** [damongolding/immich-kiosk#49]
Hi! I have my kiosk config like this:
```
  - type: panel
    title: Photo frame kiosk
    path: photo-frame-kiosk
    icon: mdi:image-frame
    subview: true
    cards:
      - type: iframe
        url: https://immich-kiosk.tld
        aspect_ratio: 50%
``` 

and trying to cast to Google Nest like this:
```
action: cast.show_lovelace_view
metadata: {}
data:
  entity_id: media_player.nesthub
  dashboard_path: lovelace
  view_path: photo-frame-kiosk
enabled: true
``` 

But a white screen is showed instead. Any other dashboard is properly casted.
Thanks
