### ISSUE TITLE
Images are not changing

### ISSUE THREAD

**Issue by bladecell** [damongolding/immich-kiosk#60]
Hey, I have set up the kiosk in version 0.7.0, but the images do not change no matter what albums, params, refresh params I put in the url or env.
Also setting the password env param and then using it in the url makes me stuck on the logo and no image gets displayed.
I have also tried the config.yaml with no luck.

compose file:

```
  immich-kiosk:
    image: damongolding/immich-kiosk:latest
    container_name: immich-kiosk
    environment:
      KIOSK_IMMICH_API_KEY: "{}"
      KIOSK_IMMICH_URL: "http://{}:2283/"
      KIOSK_REFRESH: 15
      KIOSK_ALBUM: ""
      KIOSK_PERSON: ""
      KIOSK_FILL_SCREEN: TRUE
      KIOSK_SHOW_DATE: TRUE
      KIOSK_DATE_FORMAT: DD.MM.YYYY
      KIOSK_SHOW_TIME: TRUE
      KIOSK_TIME_FORMAT: 24
      KIOSK_BACKGROUND_BLUR: TRUE
      KIOSK_TRANSITION: fade
      KIOSK_SHOW_IMAGE_TIME: TRUE
      KIOSK_IMAGE_TIME_FORMAT: 24
      KIOSK_SHOW_IMAGE_DATE: TRUE
      KIOSK_IMAGE_DATE_FORMAT: DD.MM.YYYY
    ports:
      - 3044:3000
    restart: on-failure
```

logs
```
all values are hidden
888    d8P  d8b                   888
888   d8P   Y8P                   888
888  d8P                          888
888d88K     888  .d88b.  .d8888b  888  888
8888888b    888 d88""88b 88K      888 .88P
888  Y88b   888 888  888 "Y8888b. 888888K
888   Y88b  888 Y88..88P      X88 888 "88b
888    Y88b 888  "Y88P"   88888P' 888  888
Version 0.7.0
all values are hidden
⇨ http server started on [::]:3000
```
